name: Manual deploy Lambda "Alert to slack"
on:
  workflow_dispatch:
    inputs:
      service_build:
        description: 'Deploy Lambda'
        required: true
        default: 'Deploy Lambda'
        
env:
  AWS_ROLE: ${{ secrets.AWS_LAMBDA_ROLE }}
  UNENCRYPTED_HOOK_URL: ${{ secrets.UNENCRYPTED_HOOK_URL }}
  AWS_FUNCTION_NAME: ${{ vars.AWS_FUNCTION_NAME }}
jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Prod account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: us-east-1
    - name: run list lambdas
      run: |
        npm install
        npm run deploy
     
